Add/kicker
frc2357/FRC-2022 pull request #28
Opened 2022-03-05 19:54 UTC by Tyson453

2022-03-05 19:59 UTC, NolanCampbell2357 requested changes

2022-03-05 19:59 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/subsystems/KickerSubsystem.java
> +    public void runKickermotor(double speed) {
Should be ```runKickerMotor```

2022-03-05 20:45 UTC, NolanCampbell2357 approved these changes
Good

2022-03-06 22:13 UTC, coderkevin approved these changes

2022-03-06 22:14 UTC, merged