Add shooter subsystem
frc2357/FRC-2022 pull request #9
Opened 2022-01-26 00:25 UTC by NolanCampbell2357

Currently a draft. WIP.

2022-03-01 04:01 UTC, coderkevin requested changes
In general, looks good. A few questions though.

2022-03-06 15:41 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/Constants.java
> +            config.m_shooterGearingRatio = 0;
Fixed

2022-03-06 15:41 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
> +            return;
Yes, we can.

2022-03-06 15:49 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
> +        m_leftBottomMotor.set(ControlMode.PercentOutput, output);
We can do RPMs in open loop since the Falcon 500s just won't work if their encoders do not work, so this method is gone now.

2022-03-06 15:50 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
> +    public double getShooterRPMs() {
Correct.

2022-03-06 15:50 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
> +    public double getMotorSpeed(WPI_TalonFX motor) {
Yes.

2022-03-06 15:50 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
> +    public void setVisionTarget(VisionTargetSupplier targetSupplier) {
Yes.

2022-03-06 15:51 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
> +    private double m_minutesTo100MS = 600;
I am making this a class constant, so it is not coupled to the Constants class

2022-03-06 15:52 UTC, NolanCampbell2357 commented on robotbase/src/main/java/com/team2357/frc2022/subsystems/ShooterSubsystem.java
> +            bottomRpms = m_lastVisionRPMs;
An error it is then.

2022-03-06 22:22 UTC, coderkevin approved these changes
Just a couple small things. Pre-approving

2022-03-06 22:22 UTC, coderkevin commented on robotbase/src/main/java/com/team2357/frc2022/Constants.java
> +            config.m_topShooterGearingRatio = 1/2;
Should be `1.3/1` and `2/1`

2022-03-06 22:22 UTC, coderkevin commented on robotbase/src/main/java/com/team2357/frc2022/controls/GunnerControls.java
> +                        new ShooterSetRPMsCommand(m_shooterSub, 2250, 2750));
Not sure we want magic numbers here, but I'm guessing this is just for test, right? Maybe add a // TODO: Comment above it?

2022-03-07 00:10 UTC, merged